const express = require('express');
const cors = require('cors');
const path = require('path');
const { PrismaClient } = require('@prisma/client');
const nodemailer = require('nodemailer');
const helmet = require('helmet');
require('dotenv').config();

const app = express();
const prisma = new PrismaClient();
const PORT = process.env.PORT || 5000;

// Security & Middleware
app.use(helmet({
  contentSecurityPolicy: false, // Disabled for simple image loading in this demo
}));
app.use(cors());
app.use(express.json());

// --- API ROUTES ---

// 1. Submit Lead
app.post('/api/leads', async (req, res) => {
  const { name, company, email, phone, message, productType } = req.body;
  
  if (!name || !phone || !email) {
    return res.status(400).json({ error: "Missing critical fields" });
  }

  try {
    const lead = await prisma.lead.create({
      data: { name, company, email, phone, message, productType }
    });
    
    // Logic for Email/WhatsApp alerts goes here (omitted for brevity, see previous context)
    
    console.log(`[LEAD CAPTURED] ID: ${lead.id} | ${company}`);
    return res.status(200).json({ success: true, id: lead.id });
  } catch (error) {
    console.error("DB Error:", error);
    return res.status(500).json({ error: "Internal Server Error" });
  }
});

// 2. Admin Stats (Protected logic needed in prod)
app.get('/api/admin/stats', async (req, res) => {
  try {
    const total = await prisma.lead.count();
    const recent = await prisma.lead.findMany({ take: 5, orderBy: { createdAt: 'desc' } });
    res.json({ total, recent });
  } catch (error) {
    res.status(500).json({ error: "Stats failed" });
  }
});

// --- SERVE FRONTEND (Production) ---
// Serves static assets generated by Next.js 'export'
if (process.env.NODE_ENV === 'production') {
  app.use(express.static(path.join(__dirname, 'client/out')));
  
  app.get('*', (req, res) => {
    res.sendFile(path.join(__dirname, 'client/out', 'index.html'));
  });
}

app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
